# Generated by Django 5.1.3 on 2024-11-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_mantenimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='talleres',
            field=models.ManyToManyField(related_name='vehiculos', to='vehiculos.taller'),
        ),
    ]
