# Generated by Django 5.1.3 on 2024-12-01 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0003_taller_vehiculo_talleres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='foto',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='año',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='evidencia_fotografica',
            field=models.ImageField(blank=True, null=True, upload_to='evidencias/'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='factura',
            field=models.FileField(blank=True, null=True, upload_to='facturas/'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='vehiculos.vehiculo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='talleres',
            field=models.ManyToManyField(blank=True, related_name='vehiculos', to='vehiculos.taller'),
        ),
    ]
