# Generated by Django 5.1.3 on 2024-12-01 14:29

import vehiculos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0004_remove_vehiculo_fecha_creacion_remove_vehiculo_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='evidencia_fotografica',
            field=models.ImageField(blank=True, null=True, upload_to=vehiculos.models.ruta_evidencias),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='factura',
            field=models.FileField(blank=True, null=True, upload_to=vehiculos.models.ruta_facturas),
        ),
    ]
